"""feat: retour_lat retour_lon dans interventions

Revision ID: 3764d955eb71
Revises: e894eb79f3e4
Create Date: 2026-04-12 16:47:53.418223

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3764d955eb71'
down_revision = 'e894eb79f3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retour_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('retour_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('retour_lon')
        batch_op.drop_column('retour_lat')

    # ### end Alembic commands ###
