"""feat: depart_lat depart_lon dans interventions

Revision ID: 3cc9eeea7984
Revises: d3cbe7af5543
Create Date: 2026-04-12 15:38:15.508426

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc9eeea7984'
down_revision = 'd3cbe7af5543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depart_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('depart_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('depart_lon')
        batch_op.drop_column('depart_lat')

    # ### end Alembic commands ###
