"""feat: table liaison intervention personnel

Revision ID: 78435ca08486
Revises: a7df3c2ca366
Create Date: 2026-04-11 20:16:44.108624

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78435ca08486'
down_revision = 'a7df3c2ca366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_personnel')
    # ### end Alembic commands ###
