"""feat: vehicule_id dans intervention_personnel

Revision ID: d3cbe7af5543
Revises: d06eb059e57c
Create Date: 2026-04-12 12:30:44.732023

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cbe7af5543'
down_revision = 'd06eb059e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicules', ['vehicule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_personnel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicule_id')

    # ### end Alembic commands ###
