"""feat: timestamps progression intervention

Revision ID: e894eb79f3e4
Revises: 3cc9eeea7984
Create Date: 2026-04-12 16:17:18.011720

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e894eb79f3e4'
down_revision = '3cc9eeea7984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prevu_sur_place_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prevu_retour_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('prevu_retour_at')
        batch_op.drop_column('prevu_sur_place_at')

    # ### end Alembic commands ###
