"""feat: waypoints OSRM stockés en base

Revision ID: eb6b3ad4f70e
Revises: 3764d955eb71
Create Date: 2026-04-12 17:06:31.006076

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6b3ad4f70e'
down_revision = '3764d955eb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waypoints_aller_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('waypoints_retour_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('waypoints_retour_json')
        batch_op.drop_column('waypoints_aller_json')

    # ### end Alembic commands ###
