"""feat: ajout table interventions

Revision ID: fedf3e0b93d1
Revises: 023643a2cf30
Create Date: 2026-04-11 15:11:44.052475

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedf3e0b93d1'
down_revision = '023643a2cf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('incendie_batiment', 'incendie_vehicule', 'incendie_objet', 'incendie_foret', 'secours_personne', 'accident_route', 'fuite_gaz', 'inondation', 'ouverture_porte', 'sauvetage_animal', 'risque_chimique', 'constat_deces', name='interventiontypeenum'), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'vehicule_envoye', 'en_cours', 'termine', 'annule', name='interventionstatutenum'), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('geom', sa.String(), nullable=False),
    sa.Column('caserne_id', sa.Integer(), nullable=True),
    sa.Column('vehicule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caserne_id'], ['casernes.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    # ### end Alembic commands ###
